# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
# Create the license CSV file to copy into the images
- name: golang:1.24-bookworm
  script: |
    #!/usr/bin/env bash
    go install github.com/google/go-licenses@latest
    ./licensing/create_license_csv
- name: 'gcr.io/cloud-builders/docker'
  id: "build_sidecar_image_gen1"
  entrypoint: 'bash'
  args:
    - 'docker_build'
    - 'cloud_run_gen1'
    - '${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}'
    - '${_TAG_NAME}'
- name: 'gcr.io/cloud-builders/docker'
  id: "build_sidecar_image_gen2"
  entrypoint: 'bash'
  args:
    - 'docker_build'
    - 'cloud_run_gen2'
    - '${_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}'
    - '${_TAG_NAME}'
tags: ['pcap-sidecar']
options:
  logging: CLOUD_LOGGING_ONLY
