#!/usr/bin/env bash

set +x

# PCAP files directory is only required if GCS export strategy is set to use `GCS Fuse`
if [[ "$PCAP_GCS_FUSE" == true && "${PCAP_FSN_ENABLED}" == true ]]; then
    # only create the PCAP files directory in GCS if FUSE and FSN are both enabled
    while : ; do
        gcsfuse_ready=$(mount | grep --color=never "${PCAP_MNT} type fuse" | wc -l | tr -d '\n')
        [[ "${gcsfuse_ready}" == '1' ]] \
            && echo "{\"severity\":\"INFO\",\"message\":\"GCS Bucket ${PCAP_GCS_BUCKET} is now mounted at ${PCAP_MNT}\",\"sidecar\":\"${APP_SIDECAR}\",\"module\":\"${PROC_NAME}\"}" \
            && break
        echo "{\"severity\":\"WARNING\",\"message\":\"Waiting for GCS Bucket ${PCAP_GCS_BUCKET} to be mounted at ${PCAP_MNT} ...\",\"sidecar\":\"${APP_SIDECAR}\",\"module\":\"${PROC_NAME}\"}"
        sleep 0.1
    done

    mount | grep --color=never "${PCAP_MNT} type fuse"
    
    exec mkdir -pv "${PCAP_DIR}"
fi

exec echo "{\"severity\":\"NOTICE\",\"message\":\"GCS Fuse is disabled\",\"sidecar\":\"${APP_SIDECAR}\",\"module\":\"${PROC_NAME}\"}"
