#!/usr/bin/env bash

echo "PCAP_RUN=false" >> ${ENV_FILE}
echo "PCAP_GAE=true" >> ${ENV_FILE}
echo "PCAP_GKE=false" >> ${ENV_FILE}

GAE_ENV_FILE="${ENV_FILE}.gae"

# discover GAE env by inspecting container `gaeapp`
curl -s --unix-socket /docker.sock \
  '0/containers/gaeapp/json' \
  | jq -crM '.Config.Env[]' \
  | grep --color=never -E '^(GAE_|GOOGLE_|GCLOUD_).*' \
  | sort | uniq > ${GAE_ENV_FILE}

source ${GAE_ENV_FILE}

export INSTANCE_ID="${INSTANCE_ID}-${GAE_INSTANCE}"

export K_SERVICE="${GAE_SERVICE}"
export K_REVISION="${GAE_VERSION}"

_GCP_ZONE=$(${MDS_CURL}/instance/zone)
export GCP_REGION=${_GCP_ZONE##*/}

cat ${GAE_ENV_FILE} >> ${ENV_FILE}
