#!/usr/bin/env bash

set +x

if [[ "${PCAP_FSN_ENABLED}" == true ]]; then
    # only wait for PCAP FSN if it is enabled
    while : ; do
        pcapfsn_ready=$(ps -efa | grep --color=never '/pcapfsn' | grep --color=never -v grep | wc -l  | tr -d '\n')
        [[ "${pcapfsn_ready}" == '1' ]] \
            && echo "{\"severity\":\"INFO\",\"message\":\"PCAP FS notifier is running\",\"sidecar\":\"${APP_SIDECAR}\",\"module\":\"${PROC_NAME}\"}" \
            && break
        echo "{\"severity\":\"WARNING\",\"message\":\"Waiting for PCAP FS notifier to run ...\",\"sidecar\":\"${APP_SIDECAR}\",\"module\":\"${PROC_NAME}\"}"
        sleep 0.1
    done
fi

EPHEMERAL_PORT_RANGE=`cat /proc/sys/net/ipv4/ip_local_port_range | tr '\t' ' ' | tr -s ' ' | tr ' ' ',' | tr -d '\n'`

export PCAP_IFACE_SAFE="${PCAP_IFACE:-eth}"
if [[ "${PCAP_RT_ENV}" == "cloud_run_gen1" ]]; then
    # make execution safe for Cloud Run gen1
    unset PCAP_IFACE_SAFE
    unset PCAP_COMPAT
    export PCAP_IFACE_SAFE='any'
    export PCAP_COMPAT='true'
fi

if [[ "${PCAP_DEBUG}" == true ]]; then
    ls -l /bin/tcpdump
    ls -l /bin/tcpdumpw
fi

set -x

# `exec` allows `/bin/tcpdumpw` to receive signals directly
exec env /bin/tcpdumpw \
    -verbosity="${PCAP_VERBOSITY:-DEBUG}" \
    -debug="${PCAP_DEBUG:-false}" \
    -env="${PCAP_EXEC_ENV:-run}" \
    -run=${PCAP_RUN:-true} \
    -gae=${PCAP_GAE:-false} \
    -gke=${PCAP_GKE:-false} \
    -iface="${PCAP_IFACE_SAFE}" \
    -use_cron=${PCAP_USE_CRON:-false} \
    -cron_exp="${PCAP_CRON_EXP:--}" \
    -timezone="${PCAP_TZ:-UTC}" \
    -timeout=${PCAP_TO:-0} \
    -interval=${PCAP_SECS} \
    -directory=${PCAP_TMP:-/pcap-tmp} \
    -extension=${PCAP_EXT:-pcap} \
    -tcpdump=${PCAP_TCPDUMP:-true} \
    -jsondump=${PCAP_JSONDUMP:-false} \
    -jsonlog=${PCAP_JSONDUMP_LOG:-false} \
    -ordered=${PCAP_ORDERED:-false} \
    -conntrack=${PCAP_CONNTRACK:-false} \
    -snaplen=${PCAP_SNAPLEN:-65536} \
    -hc_port="${PCAP_HC_PORT:-12345}" \
    -filter="${PCAP_FILTER:-DISABLED}" \
    -l3_protos="${PCAP_L3_PROTOS:-ipv4,ipv6}" \
    -l4_protos="${PCAP_L4_PROTOS:-tcp,udp}" \
    -ipv4="${PCAP_IPV4:-ALL}" \
    -ipv6="${PCAP_IPV6:-ALL}" \
    -hosts="${PCAP_HOSTS:-ALL}" \
    -ports="${PCAP_PORTS:-ALL}" \
    -tcp_flags="${PCAP_TCP_FLAGS:-ANY}" \
    -ephemerals="${EPHEMERAL_PORT_RANGE:-32768,65535}" \
    -rt_env="${PCAP_RT_ENV:-cloud_run_gen2}" \
    -compat="${PCAP_COMPAT:-false}" \
    -supervisor="http://127.0.0.1:${PCAP_SUPERVISOR_PORT:-23456}" \
    -no_procs="${PCAP_TCPDUMPW_NO_PROCS:-gcsfuse}" \
    -no_procs_interval="${PCAP_TCPDUMPW_NO_PROCS_INTERVAL:-15}" \
    -no_procs_debug="${PCAP_TCPDUMPW_NO_PROCS_DEBUG:-$PCAP_DEBUG}"
